/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/_student/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedLeaderRouteRouteImport } from './routes/_authenticated/leader/route'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedStudentAppRouteImport } from './routes/_authenticated/_student/app'
import { Route as AuthenticatedStudentMerchandiseRouteImport } from './routes/_authenticated/_student/merchandise'
import { Route as AuthenticatedStudentMyMembershipRouteImport } from './routes/_authenticated/_student/my-membership'
import { Route as AuthenticatedStudentMyOrdersRouteImport } from './routes/_authenticated/_student/my-orders'
import { Route as AuthenticatedStudentMyTasksRouteImport } from './routes/_authenticated/_student/my-tasks'
import { Route as AuthenticatedStudentMyTicketsRouteImport } from './routes/_authenticated/_student/my-tickets'
import { Route as AuthenticatedStudentMyVolunteerApplicationsRouteImport } from './routes/_authenticated/_student/my-volunteer-applications'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin/attendance'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminMembershipsRouteImport } from './routes/_authenticated/admin/memberships'
import { Route as AuthenticatedAdminMerchandiseRouteImport } from './routes/_authenticated/admin/merchandise'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin/tasks'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminVolunteersRouteImport } from './routes/_authenticated/admin/volunteers'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedLeaderAnnouncementsRouteImport } from './routes/_authenticated/leader/announcements'
import { Route as AuthenticatedLeaderAttendanceRouteImport } from './routes/_authenticated/leader/attendance'
import { Route as AuthenticatedLeaderDashboardRouteImport } from './routes/_authenticated/leader/dashboard'
import { Route as AuthenticatedLeaderEventsRouteImport } from './routes/_authenticated/leader/events'
import { Route as AuthenticatedLeaderTasksRouteImport } from './routes/_authenticated/leader/tasks'
import { Route as AuthenticatedLeaderVolunteersRouteImport } from './routes/_authenticated/leader/volunteers'
import { Route as AuthenticatedEventsEventIdIndexRouteImport } from './routes/_authenticated/events/$eventId/index'
import { Route as AuthenticatedEventsEventIdScannerRouteImport } from './routes/_authenticated/events/$eventId/scanner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/_student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderRouteRoute =
  AuthenticatedLeaderRouteRouteImport.update({
    id: '/leader',
    path: '/leader',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentAppRoute = AuthenticatedStudentAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedStudentRouteRoute,
} as any)
const AuthenticatedStudentMerchandiseRoute =
  AuthenticatedStudentMerchandiseRouteImport.update({
    id: '/merchandise',
    path: '/merchandise',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentMyMembershipRoute =
  AuthenticatedStudentMyMembershipRouteImport.update({
    id: '/my-membership',
    path: '/my-membership',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentMyOrdersRoute =
  AuthenticatedStudentMyOrdersRouteImport.update({
    id: '/my-orders',
    path: '/my-orders',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentMyTasksRoute =
  AuthenticatedStudentMyTasksRouteImport.update({
    id: '/my-tasks',
    path: '/my-tasks',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentMyTicketsRoute =
  AuthenticatedStudentMyTicketsRouteImport.update({
    id: '/my-tickets',
    path: '/my-tickets',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentMyVolunteerApplicationsRoute =
  AuthenticatedStudentMyVolunteerApplicationsRouteImport.update({
    id: '/my-volunteer-applications',
    path: '/my-volunteer-applications',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMembershipsRoute =
  AuthenticatedAdminMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMerchandiseRoute =
  AuthenticatedAdminMerchandiseRouteImport.update({
    id: '/merchandise',
    path: '/merchandise',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminVolunteersRoute =
  AuthenticatedAdminVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderAnnouncementsRoute =
  AuthenticatedLeaderAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  } as any)
const AuthenticatedLeaderAttendanceRoute =
  AuthenticatedLeaderAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  } as any)
const AuthenticatedLeaderDashboardRoute =
  AuthenticatedLeaderDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  } as any)
const AuthenticatedLeaderEventsRoute =
  AuthenticatedLeaderEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  } as any)
const AuthenticatedLeaderTasksRoute =
  AuthenticatedLeaderTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  } as any)
const AuthenticatedLeaderVolunteersRoute =
  AuthenticatedLeaderVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  } as any)
const AuthenticatedEventsEventIdIndexRoute =
  AuthenticatedEventsEventIdIndexRouteImport.update({
    id: '/events/$eventId/',
    path: '/events/$eventId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdScannerRoute =
  AuthenticatedEventsEventIdScannerRouteImport.update({
    id: '/events/$eventId/scanner',
    path: '/events/$eventId/scanner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/leader': typeof AuthenticatedLeaderRouteRouteWithChildren
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/app': typeof AuthenticatedStudentAppRoute
  '/merchandise': typeof AuthenticatedStudentMerchandiseRoute
  '/my-membership': typeof AuthenticatedStudentMyMembershipRoute
  '/my-orders': typeof AuthenticatedStudentMyOrdersRoute
  '/my-tasks': typeof AuthenticatedStudentMyTasksRoute
  '/my-tickets': typeof AuthenticatedStudentMyTicketsRoute
  '/my-volunteer-applications': typeof AuthenticatedStudentMyVolunteerApplicationsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/admin/merchandise': typeof AuthenticatedAdminMerchandiseRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/leader/announcements': typeof AuthenticatedLeaderAnnouncementsRoute
  '/leader/attendance': typeof AuthenticatedLeaderAttendanceRoute
  '/leader/dashboard': typeof AuthenticatedLeaderDashboardRoute
  '/leader/events': typeof AuthenticatedLeaderEventsRoute
  '/leader/tasks': typeof AuthenticatedLeaderTasksRoute
  '/leader/volunteers': typeof AuthenticatedLeaderVolunteersRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/events/$eventId/scanner': typeof AuthenticatedEventsEventIdScannerRoute
  '/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/leader': typeof AuthenticatedLeaderRouteRouteWithChildren
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/app': typeof AuthenticatedStudentAppRoute
  '/merchandise': typeof AuthenticatedStudentMerchandiseRoute
  '/my-membership': typeof AuthenticatedStudentMyMembershipRoute
  '/my-orders': typeof AuthenticatedStudentMyOrdersRoute
  '/my-tasks': typeof AuthenticatedStudentMyTasksRoute
  '/my-tickets': typeof AuthenticatedStudentMyTicketsRoute
  '/my-volunteer-applications': typeof AuthenticatedStudentMyVolunteerApplicationsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/admin/merchandise': typeof AuthenticatedAdminMerchandiseRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/leader/announcements': typeof AuthenticatedLeaderAnnouncementsRoute
  '/leader/attendance': typeof AuthenticatedLeaderAttendanceRoute
  '/leader/dashboard': typeof AuthenticatedLeaderDashboardRoute
  '/leader/events': typeof AuthenticatedLeaderEventsRoute
  '/leader/tasks': typeof AuthenticatedLeaderTasksRoute
  '/leader/volunteers': typeof AuthenticatedLeaderVolunteersRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/events/$eventId/scanner': typeof AuthenticatedEventsEventIdScannerRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/leader': typeof AuthenticatedLeaderRouteRouteWithChildren
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/_student/app': typeof AuthenticatedStudentAppRoute
  '/_authenticated/_student/merchandise': typeof AuthenticatedStudentMerchandiseRoute
  '/_authenticated/_student/my-membership': typeof AuthenticatedStudentMyMembershipRoute
  '/_authenticated/_student/my-orders': typeof AuthenticatedStudentMyOrdersRoute
  '/_authenticated/_student/my-tasks': typeof AuthenticatedStudentMyTasksRoute
  '/_authenticated/_student/my-tickets': typeof AuthenticatedStudentMyTicketsRoute
  '/_authenticated/_student/my-volunteer-applications': typeof AuthenticatedStudentMyVolunteerApplicationsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/_authenticated/admin/merchandise': typeof AuthenticatedAdminMerchandiseRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/volunteers': typeof AuthenticatedAdminVolunteersRoute
  '/_authenticated/leader/announcements': typeof AuthenticatedLeaderAnnouncementsRoute
  '/_authenticated/leader/attendance': typeof AuthenticatedLeaderAttendanceRoute
  '/_authenticated/leader/dashboard': typeof AuthenticatedLeaderDashboardRoute
  '/_authenticated/leader/events': typeof AuthenticatedLeaderEventsRoute
  '/_authenticated/leader/tasks': typeof AuthenticatedLeaderTasksRoute
  '/_authenticated/leader/volunteers': typeof AuthenticatedLeaderVolunteersRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/events/$eventId/scanner': typeof AuthenticatedEventsEventIdScannerRoute
  '/_authenticated/events/$eventId/': typeof AuthenticatedEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/leader'
    | '/announcements'
    | '/profile'
    | '/app'
    | '/merchandise'
    | '/my-membership'
    | '/my-orders'
    | '/my-tasks'
    | '/my-tickets'
    | '/my-volunteer-applications'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/memberships'
    | '/admin/merchandise'
    | '/admin/orders'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/volunteers'
    | '/leader/announcements'
    | '/leader/attendance'
    | '/leader/dashboard'
    | '/leader/events'
    | '/leader/tasks'
    | '/leader/volunteers'
    | '/events/'
    | '/events/$eventId/scanner'
    | '/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/leader'
    | '/announcements'
    | '/profile'
    | '/app'
    | '/merchandise'
    | '/my-membership'
    | '/my-orders'
    | '/my-tasks'
    | '/my-tickets'
    | '/my-volunteer-applications'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/memberships'
    | '/admin/merchandise'
    | '/admin/orders'
    | '/admin/tasks'
    | '/admin/users'
    | '/admin/volunteers'
    | '/leader/announcements'
    | '/leader/attendance'
    | '/leader/dashboard'
    | '/leader/events'
    | '/leader/tasks'
    | '/leader/volunteers'
    | '/events'
    | '/events/$eventId/scanner'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/_student'
    | '/_authenticated/admin'
    | '/_authenticated/leader'
    | '/_authenticated/announcements'
    | '/_authenticated/profile'
    | '/_authenticated/_student/app'
    | '/_authenticated/_student/merchandise'
    | '/_authenticated/_student/my-membership'
    | '/_authenticated/_student/my-orders'
    | '/_authenticated/_student/my-tasks'
    | '/_authenticated/_student/my-tickets'
    | '/_authenticated/_student/my-volunteer-applications'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/memberships'
    | '/_authenticated/admin/merchandise'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/volunteers'
    | '/_authenticated/leader/announcements'
    | '/_authenticated/leader/attendance'
    | '/_authenticated/leader/dashboard'
    | '/_authenticated/leader/events'
    | '/_authenticated/leader/tasks'
    | '/_authenticated/leader/volunteers'
    | '/_authenticated/events/'
    | '/_authenticated/events/$eventId/scanner'
    | '/_authenticated/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_student': {
      id: '/_authenticated/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedStudentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leader': {
      id: '/_authenticated/leader'
      path: '/leader'
      fullPath: '/leader'
      preLoaderRoute: typeof AuthenticatedLeaderRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_student/app': {
      id: '/_authenticated/_student/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedStudentAppRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/merchandise': {
      id: '/_authenticated/_student/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof AuthenticatedStudentMerchandiseRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/my-membership': {
      id: '/_authenticated/_student/my-membership'
      path: '/my-membership'
      fullPath: '/my-membership'
      preLoaderRoute: typeof AuthenticatedStudentMyMembershipRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/my-orders': {
      id: '/_authenticated/_student/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof AuthenticatedStudentMyOrdersRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/my-tasks': {
      id: '/_authenticated/_student/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AuthenticatedStudentMyTasksRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/my-tickets': {
      id: '/_authenticated/_student/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof AuthenticatedStudentMyTicketsRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/my-volunteer-applications': {
      id: '/_authenticated/_student/my-volunteer-applications'
      path: '/my-volunteer-applications'
      fullPath: '/my-volunteer-applications'
      preLoaderRoute: typeof AuthenticatedStudentMyVolunteerApplicationsRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/memberships': {
      id: '/_authenticated/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AuthenticatedAdminMembershipsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/merchandise': {
      id: '/_authenticated/admin/merchandise'
      path: '/merchandise'
      fullPath: '/admin/merchandise'
      preLoaderRoute: typeof AuthenticatedAdminMerchandiseRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/volunteers': {
      id: '/_authenticated/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AuthenticatedAdminVolunteersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leader/announcements': {
      id: '/_authenticated/leader/announcements'
      path: '/announcements'
      fullPath: '/leader/announcements'
      preLoaderRoute: typeof AuthenticatedLeaderAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedLeaderRouteRoute
    }
    '/_authenticated/leader/attendance': {
      id: '/_authenticated/leader/attendance'
      path: '/attendance'
      fullPath: '/leader/attendance'
      preLoaderRoute: typeof AuthenticatedLeaderAttendanceRouteImport
      parentRoute: typeof AuthenticatedLeaderRouteRoute
    }
    '/_authenticated/leader/dashboard': {
      id: '/_authenticated/leader/dashboard'
      path: '/dashboard'
      fullPath: '/leader/dashboard'
      preLoaderRoute: typeof AuthenticatedLeaderDashboardRouteImport
      parentRoute: typeof AuthenticatedLeaderRouteRoute
    }
    '/_authenticated/leader/events': {
      id: '/_authenticated/leader/events'
      path: '/events'
      fullPath: '/leader/events'
      preLoaderRoute: typeof AuthenticatedLeaderEventsRouteImport
      parentRoute: typeof AuthenticatedLeaderRouteRoute
    }
    '/_authenticated/leader/tasks': {
      id: '/_authenticated/leader/tasks'
      path: '/tasks'
      fullPath: '/leader/tasks'
      preLoaderRoute: typeof AuthenticatedLeaderTasksRouteImport
      parentRoute: typeof AuthenticatedLeaderRouteRoute
    }
    '/_authenticated/leader/volunteers': {
      id: '/_authenticated/leader/volunteers'
      path: '/volunteers'
      fullPath: '/leader/volunteers'
      preLoaderRoute: typeof AuthenticatedLeaderVolunteersRouteImport
      parentRoute: typeof AuthenticatedLeaderRouteRoute
    }
    '/_authenticated/events/$eventId/': {
      id: '/_authenticated/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId/scanner': {
      id: '/_authenticated/events/$eventId/scanner'
      path: '/events/$eventId/scanner'
      fullPath: '/events/$eventId/scanner'
      preLoaderRoute: typeof AuthenticatedEventsEventIdScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentAppRoute: typeof AuthenticatedStudentAppRoute
  AuthenticatedStudentMerchandiseRoute: typeof AuthenticatedStudentMerchandiseRoute
  AuthenticatedStudentMyMembershipRoute: typeof AuthenticatedStudentMyMembershipRoute
  AuthenticatedStudentMyOrdersRoute: typeof AuthenticatedStudentMyOrdersRoute
  AuthenticatedStudentMyTasksRoute: typeof AuthenticatedStudentMyTasksRoute
  AuthenticatedStudentMyTicketsRoute: typeof AuthenticatedStudentMyTicketsRoute
  AuthenticatedStudentMyVolunteerApplicationsRoute: typeof AuthenticatedStudentMyVolunteerApplicationsRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentAppRoute: AuthenticatedStudentAppRoute,
    AuthenticatedStudentMerchandiseRoute: AuthenticatedStudentMerchandiseRoute,
    AuthenticatedStudentMyMembershipRoute:
      AuthenticatedStudentMyMembershipRoute,
    AuthenticatedStudentMyOrdersRoute: AuthenticatedStudentMyOrdersRoute,
    AuthenticatedStudentMyTasksRoute: AuthenticatedStudentMyTasksRoute,
    AuthenticatedStudentMyTicketsRoute: AuthenticatedStudentMyTicketsRoute,
    AuthenticatedStudentMyVolunteerApplicationsRoute:
      AuthenticatedStudentMyVolunteerApplicationsRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminMembershipsRoute: typeof AuthenticatedAdminMembershipsRoute
  AuthenticatedAdminMerchandiseRoute: typeof AuthenticatedAdminMerchandiseRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVolunteersRoute: typeof AuthenticatedAdminVolunteersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
    AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
    AuthenticatedAdminMembershipsRoute: AuthenticatedAdminMembershipsRoute,
    AuthenticatedAdminMerchandiseRoute: AuthenticatedAdminMerchandiseRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminVolunteersRoute: AuthenticatedAdminVolunteersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedLeaderRouteRouteChildren {
  AuthenticatedLeaderAnnouncementsRoute: typeof AuthenticatedLeaderAnnouncementsRoute
  AuthenticatedLeaderAttendanceRoute: typeof AuthenticatedLeaderAttendanceRoute
  AuthenticatedLeaderDashboardRoute: typeof AuthenticatedLeaderDashboardRoute
  AuthenticatedLeaderEventsRoute: typeof AuthenticatedLeaderEventsRoute
  AuthenticatedLeaderTasksRoute: typeof AuthenticatedLeaderTasksRoute
  AuthenticatedLeaderVolunteersRoute: typeof AuthenticatedLeaderVolunteersRoute
}

const AuthenticatedLeaderRouteRouteChildren: AuthenticatedLeaderRouteRouteChildren =
  {
    AuthenticatedLeaderAnnouncementsRoute:
      AuthenticatedLeaderAnnouncementsRoute,
    AuthenticatedLeaderAttendanceRoute: AuthenticatedLeaderAttendanceRoute,
    AuthenticatedLeaderDashboardRoute: AuthenticatedLeaderDashboardRoute,
    AuthenticatedLeaderEventsRoute: AuthenticatedLeaderEventsRoute,
    AuthenticatedLeaderTasksRoute: AuthenticatedLeaderTasksRoute,
    AuthenticatedLeaderVolunteersRoute: AuthenticatedLeaderVolunteersRoute,
  }

const AuthenticatedLeaderRouteRouteWithChildren =
  AuthenticatedLeaderRouteRoute._addFileChildren(
    AuthenticatedLeaderRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedLeaderRouteRoute: typeof AuthenticatedLeaderRouteRouteWithChildren
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedEventsEventIdScannerRoute: typeof AuthenticatedEventsEventIdScannerRoute
  AuthenticatedEventsEventIdIndexRoute: typeof AuthenticatedEventsEventIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedLeaderRouteRoute: AuthenticatedLeaderRouteRouteWithChildren,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedEventsEventIdScannerRoute:
    AuthenticatedEventsEventIdScannerRoute,
  AuthenticatedEventsEventIdIndexRoute: AuthenticatedEventsEventIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
