/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/_student/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedLeaderRouteRouteImport } from './routes/_authenticated/leader/route'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedStudentAppRouteImport } from './routes/_authenticated/_student/app'
import { Route as AuthenticatedStudentMerchandiseRouteImport } from './routes/_authenticated/_student/merchandise'
import { Route as AuthenticatedStudentMyMembershipRouteImport } from './routes/_authenticated/_student/my-membership'
import { Route as AuthenticatedStudentMyOrdersRouteImport } from './routes/_authenticated/_student/my-orders'
import { Route as AuthenticatedStudentMyTasksRouteImport } from './routes/_authenticated/_student/my-tasks'
import { Route as AuthenticatedStudentMyTicketsRouteImport } from './routes/_authenticated/_student/my-tickets'
import { Route as AuthenticatedStudentMyVolunteerApplicationsRouteImport } from './routes/_authenticated/_student/my-volunteer-applications'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin/attendance'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminMembershipsRouteImport } from './routes/_authenticated/admin/memberships'
import { Route as AuthenticatedAdminMerchandiseRouteImport } from './routes/_authenticated/admin/merchandise'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin/tasks'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminVolunteersRouteImport } from './routes/_authenticated/admin/volunteers'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedLeaderAnnouncementsRouteImport } from './routes/_authenticated/leader/announcements'
import { Route as AuthenticatedLeaderAttendanceRouteImport } from './routes/_authenticated/leader/attendance'
import { Route as AuthenticatedLeaderDashboardRouteImport } from './routes/_authenticated/leader/dashboard'
import { Route as AuthenticatedLeaderEventsRouteImport } from './routes/_authenticated/leader/events'
import { Route as AuthenticatedLeaderTasksRouteImport } from './routes/_authenticated/leader/tasks'
import { Route as AuthenticatedLeaderVolunteersRouteImport } from './routes/_authenticated/leader/volunteers'
import { Route as AuthenticatedEventsEventIdIndexRouteImport } from './routes/_authenticated/events/$eventId/index'
import { Route as AuthenticatedEventsEventIdScannerRouteImport } from './routes/_authenticated/events/$eventId/scanner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
})
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
})
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/_student',
    getParentRoute: () => AuthenticatedRouteRoute,
  })
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
})
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  })
const AuthenticatedLeaderRouteRoute =
  AuthenticatedLeaderRouteRouteImport.update({
    id: '/leader',
    path: '/leader',
    getParentRoute: () => AuthenticatedRouteRoute,
  })
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
})
const AuthenticatedStudentAppRoute = AuthenticatedStudentAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedStudentRouteRoute,
})
const AuthenticatedStudentMerchandiseRoute =
  AuthenticatedStudentMerchandiseRouteImport.update({
    id: '/merchandise',
    path: '/merchandise',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  })
const AuthenticatedStudentMyMembershipRoute =
  AuthenticatedStudentMyMembershipRouteImport.update({
    id: '/my-membership',
    path: '/my-membership',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  })
const AuthenticatedStudentMyOrdersRoute =
  AuthenticatedStudentMyOrdersRouteImport.update({
    id: '/my-orders',
    path: '/my-orders',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  })
const AuthenticatedStudentMyTasksRoute =
  AuthenticatedStudentMyTasksRouteImport.update({
    id: '/my-tasks',
    path: '/my-tasks',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  })
const AuthenticatedStudentMyTicketsRoute =
  AuthenticatedStudentMyTicketsRouteImport.update({
    id: '/my-tickets',
    path: '/my-tickets',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  })
const AuthenticatedStudentMyVolunteerApplicationsRoute =
  AuthenticatedStudentMyVolunteerApplicationsRouteImport.update({
    id: '/my-volunteer-applications',
    path: '/my-volunteer-applications',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  })
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  })
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  })
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  })
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  })
const AuthenticatedAdminMembershipsRoute =
  AuthenticatedAdminMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  })
const AuthenticatedAdminMerchandiseRoute =
  AuthenticatedAdminMerchandiseRouteImport.update({
    id: '/merchandise',
    path: '/merchandise',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  })
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  })
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
})
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
})
const AuthenticatedAdminVolunteersRoute =
  AuthenticatedAdminVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  })
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  })
const AuthenticatedLeaderAnnouncementsRoute =
  AuthenticatedLeaderAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  })
const AuthenticatedLeaderAttendanceRoute =
  AuthenticatedLeaderAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  })
const AuthenticatedLeaderDashboardRoute =
  AuthenticatedLeaderDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  })
const AuthenticatedLeaderEventsRoute =
  AuthenticatedLeaderEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  })
const AuthenticatedLeaderTasksRoute =
  AuthenticatedLeaderTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  })
const AuthenticatedLeaderVolunteersRoute =
  AuthenticatedLeaderVolunteersRouteImport.update({
    id: '/volunteers',
    path: '/volunteers',
    getParentRoute: () => AuthenticatedLeaderRouteRoute,
  })
const AuthenticatedEventsEventIdIndexRoute =
  AuthenticatedEventsEventIdIndexRouteImport.update({
    id: '/events/$eventId/',
    path: '/events/$eventId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  })
const AuthenticatedEventsEventIdScannerRoute =
  AuthenticatedEventsEventIdScannerRouteImport.update({
    id: '/events/$eventId/scanner',
    path: '/events/$eventId/scanner',
    getParentRoute: () => AuthenticatedRouteRoute,
  })

const AuthenticatedStudentRouteRouteChildren = {
  AuthenticatedStudentAppRoute: AuthenticatedStudentAppRoute,
  AuthenticatedStudentMerchandiseRoute: AuthenticatedStudentMerchandiseRoute,
  AuthenticatedStudentMyMembershipRoute: AuthenticatedStudentMyMembershipRoute,
  AuthenticatedStudentMyOrdersRoute: AuthenticatedStudentMyOrdersRoute,
  AuthenticatedStudentMyTasksRoute: AuthenticatedStudentMyTasksRoute,
  AuthenticatedStudentMyTicketsRoute: AuthenticatedStudentMyTicketsRoute,
  AuthenticatedStudentMyVolunteerApplicationsRoute:
    AuthenticatedStudentMyVolunteerApplicationsRoute,
}

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

const AuthenticatedAdminRouteRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminMembershipsRoute: AuthenticatedAdminMembershipsRoute,
  AuthenticatedAdminMerchandiseRoute: AuthenticatedAdminMerchandiseRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVolunteersRoute: AuthenticatedAdminVolunteersRoute,
}

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

const AuthenticatedLeaderRouteRouteChildren = {
  AuthenticatedLeaderAnnouncementsRoute: AuthenticatedLeaderAnnouncementsRoute,
  AuthenticatedLeaderAttendanceRoute: AuthenticatedLeaderAttendanceRoute,
  AuthenticatedLeaderDashboardRoute: AuthenticatedLeaderDashboardRoute,
  AuthenticatedLeaderEventsRoute: AuthenticatedLeaderEventsRoute,
  AuthenticatedLeaderTasksRoute: AuthenticatedLeaderTasksRoute,
  AuthenticatedLeaderVolunteersRoute: AuthenticatedLeaderVolunteersRoute,
}

const AuthenticatedLeaderRouteRouteWithChildren =
  AuthenticatedLeaderRouteRoute._addFileChildren(
    AuthenticatedLeaderRouteRouteChildren,
  )

const AuthenticatedRouteRouteChildren = {
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedLeaderRouteRoute: AuthenticatedLeaderRouteRouteWithChildren,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedEventsEventIdScannerRoute:
    AuthenticatedEventsEventIdScannerRoute,
  AuthenticatedEventsEventIdIndexRoute: AuthenticatedEventsEventIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SubscribeRoute: SubscribeRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
